//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSaveNotepad.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoSaveNotepad.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text documents (.txt)|*.txt.
        /// </summary>
        public static string MainWindow_FileDialog_DocumentFilter {
            get {
                return ResourceManager.GetString("MainWindow_FileDialog_DocumentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last saved.
        /// </summary>
        public static string MainWindow_LastSaved {
            get {
                return ResourceManager.GetString("MainWindow_LastSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_MenuItem_File {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Save.
        /// </summary>
        public static string MainWindow_MenuItem_File_AutoSave {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_AutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainWindow_MenuItem_File_Exit {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+F4.
        /// </summary>
        public static string MainWindow_MenuItem_File_Exit_Shortcut_Text {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_Exit_Shortcut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainWindow_MenuItem_File_New {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+N.
        /// </summary>
        public static string MainWindow_MenuItem_File_New_Shortcut_Text {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_New_Shortcut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string MainWindow_MenuItem_File_Open {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+O.
        /// </summary>
        public static string MainWindow_MenuItem_File_Open_Shortcut_Text {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_Open_Shortcut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_MenuItem_File_Save {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+S.
        /// </summary>
        public static string MainWindow_MenuItem_File_Save_Shortcut_Text {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_Save_Shortcut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string MainWindow_MenuItem_File_SaveAs {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Shift+S.
        /// </summary>
        public static string MainWindow_MenuItem_File_SaveAs_Shortcut_Text {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_File_SaveAs_Shortcut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string MainWindow_MenuItem_RecentFiles {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_MenuItem_Settings {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string MainWindow_MenuItem_Settings_DE {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Settings_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MainWindow_MenuItem_Settings_EN {
            get {
                return ResourceManager.GetString("MainWindow_MenuItem_Settings_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document could not be opened. Please try again....
        /// </summary>
        public static string MainWindow_Open_Failed {
            get {
                return ResourceManager.GetString("MainWindow_Open_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open failed.
        /// </summary>
        public static string MainWindow_Open_Failed_Title {
            get {
                return ResourceManager.GetString("MainWindow_Open_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad.
        /// </summary>
        public static string MainWindow_PageTitle {
            get {
                return ResourceManager.GetString("MainWindow_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document could not be saved. Please try again....
        /// </summary>
        public static string MainWindow_Save_Failed {
            get {
                return ResourceManager.GetString("MainWindow_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        public static string MainWindow_Save_Failed_Title {
            get {
                return ResourceManager.GetString("MainWindow_Save_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char.
        /// </summary>
        public static string MainWindow_StatusBar_Character {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string MainWindow_StatusBar_Line {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes. Do you want to save the document now?.
        /// </summary>
        public static string MainWindow_UnsavedChanges_Message {
            get {
                return ResourceManager.GetString("MainWindow_UnsavedChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string MainWindow_UnsavedChanges_Title {
            get {
                return ResourceManager.GetString("MainWindow_UnsavedChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Language.
        /// </summary>
        public static string SwitchLanguage_Caption {
            get {
                return ResourceManager.GetString("SwitchLanguage_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application to load the selected language..
        /// </summary>
        public static string SwitchLanguage_Message {
            get {
                return ResourceManager.GetString("SwitchLanguage_Message", resourceCulture);
            }
        }
    }
}
